---
title: "Tarea Autónoma"
subtitle: "Encontrar la Pendiente de la Recta Tangente"
author: "Elvis Sánchez"
format:
  pdf:
    fontsize: 12pt
    break-on-sections: true
    documentclass: article
    include-in-header:
      text: |
        \usepackage[top=2cm, left=2.5cm, right=2.5cm, bottom=2.5cm]{geometry}
--- 

## 1. **Encontrar la pendiente de la recta tangente a la curva $y = x^2 + 2x - 3$ en los puntos de su domino a continuación listados $x_0=\{-3;-2;0;1\}$. Además de realizar la gráfica que representen a las pendientes en cada punto solicitado** 

{{<pagebreak>}}

## 1. Encontrar la Pendiente de la Recta Tangente

**Encontrar la pendiente de la recta tangente a la curva $y = x^2 + 2x - 3$ en los puntos de su domino a continuación listados $x_0=\{-3;-2;0;1\}$. Además de realizar la gráfica que representen a las pendientes en cada punto solicitado** 

**Solución:**

Como $y = f(x)$, entonces $f(x) = x^2 + 2x - 3$, donde:

$$
f(x_1) = x_1^2 + 2x_1 - 3
$$

$$
f(x_1 + \Delta x) = (x_1 + \Delta x)^2 + 2(x_1 + \Delta x) - 3
$$

Sustituyendo en la ecuación de la pendiente:

$$
m(x_1) = \lim_{\Delta x \to 0} \frac{f(x_1 + \Delta x) - f(x_1)}{\Delta x}
$$

Efectuando operaciones:

$$
m(x_1) = \lim_{\Delta x \to 0} \frac{\left[(x_1 + \Delta x)^2 + 2(x_1 + \Delta x) - 3\right] - \left[x_1^2 + 2x_1 - 3\right]}{\Delta x}
$$

Quitando paréntesis:

$$
m(x_1) = \lim_{\Delta x \to 0} \frac{x_1^2 + 2x_1\Delta x + (\Delta x)^2 + 2x_1 + 2\Delta x - 3 - x_1^2 - 2x_1 + 3}{\Delta x}
$$

Reduciendo términos semejantes:

$$
m(x_1) = \lim_{\Delta x \to 0} \frac{2x_1\Delta x + (\Delta x)^2 + 2\Delta x}{\Delta x}
$$

Como $\Delta x \to 0$, $\Delta x \neq 0$, por tanto, se puede dividir entre $\Delta x$:

$$
m(x_1) = \lim_{\Delta x \to 0} (2x_1 + \Delta x + 2)
$$

Tomando el límite:

$$
m(x_1) = 2x_1 + 2
$$

La gráfica de la función se ilustra en la siguiente figura. En ella se representan segmentos de la recta tangente en algunos puntos de la gráfica (véase figura 3.9).

Para cualquier valor de $x$ su correspondiente valor de $y$ se obtiene a partir de la ecuación $y = x^2 + 2x - 3$, mientras que el valor de la pendiente se obtiene a partir de la ecuación $m(x_1) = 2x_1 + 2$.

Así, para:

a) $x_1 = -3$
$$
y = (-3)^2 + 2(-3) - 3 = 9 - 6 - 3 = 0 \quad m(-3) = 2(-3) + 2 = -6 + 2 = -4
$$
Es decir, que cuando $x = -3$, su ordenada correspondiente es $y = 0$ por lo que para el punto $(-3, 0)$ de la curva, la recta tangente en dicho punto tiene pendiente $m = -4$.

b) $x_1 = -2$
$$
y = (-2)^2 + 2(-2) - 3 = 4 - 4 - 3 = -3 \quad m(-2) = 2(-2) + 2 = -4 + 2 = -2
$$
De manera que para $x = -2$, $y = -3$, o sea que en el punto $(-2, -3)$ de la curva la recta tangente en dicho punto tiene pendiente $m = -2$.

c) $x_1 = 0$
$$
y = 0^2 + 2(0) - 3 = 0 + 0 - 3 = -3 \quad m(0) = 2(0) + 2 = 0 + 2 = 2
$$
Por tanto, en el punto $(0, -3)$ de la curva, la recta tangente tiene pendiente $m = 2$.

d) $x_1 = 1$
$$
y = 1^2 + 2(1) - 3 = 1 + 2 - 3 = 0 \quad m(1) = 2(1) + 2 = 2 + 2 = 4
$$
Entonces, en el punto $(1, 0)$ de la curva, la recta tangente tiene pendiente $m = 4$.

Es de particular importancia determinar los puntos donde la gráfica tiene una tangente horizontal, pues ésta tiene pendiente cero. Dichos puntos se obtienen al hacer $m(x_1) = 0$ y resolver para $x_1$.

En este ejemplo se tiene que:
$$
m(x_1) = 2x_1 + 2
$$
Es decir:
$$
m(x_1) = 0
$$
$$
0 = 2x_1 + 2
$$
De donde:
$$
-2 = 2x_1
$$
$$
\frac{-2}{2} = x_1
$$
Por tanto:
$$
x_1 = -1
$$
O bien:
$$
x_1 = -1
$$
Esto significa que en el punto de la curva que tiene su abscisa igual a $-1$, la recta tangente es paralela al eje de las $x$.

{{<pagebreak>}}

## 2. Obtén la ecuación de la recta tangente

**Obtén la ecuación de la recta tangente a la curva $y = x^2 + 2x - 3$ en el punto $(-2, -3)$.**

**Solución:**

La curva $y = x^2 + 2x - 3$ es la misma del ejemplo anterior. Para ella se determinó que en cualquiera de sus puntos $(x_1, y_1)$ la pendiente de la recta tangente es:

$$
m(x_1) = 2x_1 + 2
$$

En el punto $(-2, -3)$ de la curva, la pendiente de la recta tangente es:

$$
\begin{aligned}
m(-2) &= 2(-2) + 2 \\
      &= -4 + 2 \\
      &= -2
\end{aligned}
$$

Utilizando la ecuación de la recta en la forma punto – pendiente:

$$
y - y_1 = m(x - x_1)
$$

Se tiene que la ecuación de la recta tangente es:

$$
\begin{aligned}
y - (-3) &= -2(x - (-2)) \\
y + 3 &= -2(x + 2)
\end{aligned}
$$

De donde:

$$
y + 3 = -2x - 4
$$

O bien:

$$
2x + y + 7 = 0
$$

Una recta normal (perpendicular) en un punto de una curva es la recta perpendicular a la recta tangente en ese punto.


